eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-service.stock-quote-tp.appspot.com/eureka/
  instance:
    hostname: eureka-service.stock-quote-tp.appspot.com

management:
  server:
    servlet:
      context-path: /_ah
